version: '2'
services:
    ra_bbvet-mysql:
        container_name: ra_bbvet-mysql
        image: mysql:5.7.12
        # volumes:
        #     - ~/volumes/jhipster/ra_bbvet/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=ra_bbvet
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
